# Generated by Django 4.2.6 on 2023-10-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_value',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_value',
        ),
        migrations.AddField(
            model_name='country',
            name='phonecode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
